require('./utilities/console.cti+.schemas')
require('./utilities/console.cti+.tokens')
require('./utilities/name.cti+.camel')
require('./utilities/name.cti+.kebab')
require('./utilities/name.cti+.pascal')
require('./utilities/name.cti+.snake')