const { ENV, COLOR } = require('../../constants')
const { schema } = require('../helpers')

const meta = { domain: ENV.DOMAIN.SYSTEM, class: COLOR.CLASS, subclass: COLOR.SUBCLASS.PALETTE }

const PRIMARY = [
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "primary", subitem: null, state: "900", context: null }),
]

const SECONDARY = [
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "secondary", subitem: null, state: "900", context: null }),
]

const TERTIARY = [
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "tertiary", subitem: null, state: "900", context: null }),
]

const POSITIVE = [
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "positive", subitem: null, state: "900", context: null }),
]

const NEGATIVE = [
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "negative", subitem: null, state: "900", context: null }),
]
const HIGHLIGHT = [
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "highlight", subitem: null, state: "900", context: null }),
]

const ATTENTION = [
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "attention", subitem: null, state: "900", context: null }),
]

const INFO = [
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "info", subitem: null, state: "900", context: null }),
]

const SYSTEM = [
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "system", subitem: null, state: "900", context: null }),
]

const NEUTRAL = [
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "000", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "015", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "025", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "050", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "075", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "085", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "100", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "200", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "300", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "400", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "500", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "600", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "700", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "800", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "900", context: null }),
    schema(meta, { type: null, item: null, variant: "neutral", subitem: null, state: "950", context: null }),
]

module.exports = [
    ...PRIMARY,
    ...SECONDARY,
    ...TERTIARY,
    ...POSITIVE,
    ...NEGATIVE,
    ...HIGHLIGHT,
    ...ATTENTION,
    ...INFO,
    ...SYSTEM,
    ...NEUTRAL,
    // ...LIGHTEN,
    // ...DARKEN
] 